/**
 * ChangelogService — generates a Markdown or plain-text CHANGELOG from
 * resolved/closed issues, optionally filtered to a specific version range.
 *
 * © 2024 Vetspresso — Alberto L. Bonfiglio
 * AGPL-3.0-only
 */

import { IssueDatabase } from '../database/IssueDatabase';
import { Issue, IssueType } from '../types';
import { shortDate } from '../utils/helpers';

export interface ChangelogOptions {
    /** Only include issues fixed in this version.  Omit for all versions. */
    version?: string;
    /** Include issues from this version onward (inclusive, semver string). */
    sinceVersion?: string;
    /** Whether to group entries by issue type.  Default: true. */
    groupByType?: boolean;
    /** Whether to include the "reported in" version for each entry. */
    includeReportedIn?: boolean;
}

/** A single section of the changelog (one version). */
export interface ChangelogSection {
    version: string;
    date: string | null;
    issues: Issue[];
}

const TYPE_HEADING: Record<IssueType, string> = {
    bug: '### Bug Fixes',
    enhancement: '### Enhancements',
    feature: '### New Features',
    task: '### Tasks',
    question: '### Questions / Clarifications',
    documentation: '### Documentation',
    other: '### Other Changes',
};

const TYPE_ORDER: IssueType[] = [
    'feature',
    'enhancement',
    'bug',
    'task',
    'documentation',
    'question',
    'other',
];

export class ChangelogService {
    constructor(private readonly db: IssueDatabase) { }

    /**
     * Returns grouped changelog sections (one per fixedInVersion value),
     * sorted newest-version-first.
     */
    buildSections(options: ChangelogOptions = {}): ChangelogSection[] {
        const allIssues = this.db.getAllIssues().filter(
            (i) => i.status === 'resolved' || i.status === 'closed'
        );

        const byVersion = new Map<string, Issue[]>();

        for (const issue of allIssues) {
            const ver = issue.fixedInVersion ?? 'Unreleased';
            if (options.version && ver !== options.version) {
                continue;
            }
            if (!byVersion.has(ver)) {
                byVersion.set(ver, []);
            }
            byVersion.get(ver)?.push(issue);
        }

        const sections: ChangelogSection[] = [];
        for (const [version, issues] of byVersion) {
            const latestResolvedAt = issues
                .map((i) => i.resolvedAt)
                .filter((d): d is string => d !== null)
                .sort()
                .at(-1) ?? null;

            sections.push({
                version,
                date: latestResolvedAt ? shortDate(latestResolvedAt) : null,
                issues: issues.sort((a, b) => a.sequentialId - b.sequentialId),
            });
        }

        // Sort: "Unreleased" first, then descending by version string
        sections.sort((a, b) => {
            if (a.version === 'Unreleased') { return -1; }
            if (b.version === 'Unreleased') { return 1; }
            return b.version.localeCompare(a.version, undefined, { numeric: true });
        });

        return sections;
    }

    /**
     * Renders a full CHANGELOG.md-compatible Markdown document.
     */
    renderMarkdown(options: ChangelogOptions = {}): string {
        const sections = this.buildSections(options);
        if (sections.length === 0) {
            return '# Changelog\n\nNo resolved issues found.\n';
        }

        const lines: string[] = ['# Changelog', '', '> Auto-generated by Vetspresso Issues Tracker', ''];

        for (const section of sections) {
            const title = section.date
                ? `## ${section.version} — ${section.date}`
                : `## ${section.version}`;
            lines.push(title, '');

            if (options.groupByType !== false) {
                // Group by type
                const grouped = new Map<IssueType, Issue[]>();
                for (const issue of section.issues) {
                    const group = grouped.get(issue.type) ?? [];
                    group.push(issue);
                    grouped.set(issue.type, group);
                }

                for (const type of TYPE_ORDER) {
                    const group = grouped.get(type);
                    if (!group || group.length === 0) { continue; }
                    lines.push(TYPE_HEADING[type], '');
                    for (const issue of group) {
                        lines.push(this.formatEntry(issue, options));
                    }
                    lines.push('');
                }
            } else {
                for (const issue of section.issues) {
                    lines.push(this.formatEntry(issue, options));
                }
                lines.push('');
            }
        }

        return lines.join('\n');
    }

    /**
     * Renders a minimal plain-text changelog suitable for release notes.
     */
    renderPlainText(options: ChangelogOptions = {}): string {
        const sections = this.buildSections(options);
        if (sections.length === 0) {
            return 'No resolved issues found.\n';
        }

        const lines: string[] = [];
        for (const section of sections) {
            const title = section.date
                ? `${section.version} (${section.date})`
                : section.version;
            lines.push(title);
            lines.push('='.repeat(title.length));
            for (const issue of section.issues) {
                lines.push(`  [${issue.type.toUpperCase()}] #${issue.sequentialId} ${issue.title}`);
            }
            lines.push('');
        }
        return lines.join('\n');
    }

    private formatEntry(issue: Issue, options: ChangelogOptions): string {
        let entry = `- **#${issue.sequentialId}** ${issue.title}`;
        if (options.includeReportedIn && issue.reportedInVersion) {
            entry += ` _(reported in ${issue.reportedInVersion})_`;
        }
        if (issue.assignedTo) {
            entry += ` — by @${issue.assignedTo}`;
        }
        return entry;
    }
}
